# -*- coding: utf-8 -*-
"""project1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-H3jhQw8QokgL0dE3Yv8I5q0d41Jpm3C
"""

import pandas as pd
 import numpy as np
 import matplotlib.pyplot as plt
 import seaborn as sns

df = pd.read_csv("Banking.csv")

df.head()

df.describe()

df['Estimated Income'].max()

bins = [ 0, 100000, 300000 ,float('inf')]
labels = ['Low', 'Medium', 'High']
df['Income Band'] = pd.cut(df['Estimated Income'], bins=bins, labels=labels, right=False)

df['Income Band'].value_counts().plot(kind='bar', title='Income Band')

"""# Examine the unique categories in catgorical coulmns

"""

categorical_cols= df[['BRId', "GenderId","IAId", "Amount of Credit Cards", "Nationality","Occupation", "Fee Structure","Loyalty Classification","Properties Owned", "Risk Weighting", "Income Band"]].columns

for col in categorical_cols:
    print(f"Value counts in {col}:")
    display(df[col].value_counts())

for i , predictor in enumerate(df):
  plt.figure(i)
  sns.countplot(data=df, x=predictor , hue ='Nationality')

for col in categorical_cols:
    if col == 'Occupation':
      continue
    plt.figure(figsize=(8, 4))
    sns.histplot(df[col])
    plt.title('histogram of Occupation count')
    plt.xlabel(col)
    plt.ylabel('count')
    plt.show()

"""#Numerical Analysis

"""

numerical_cols=['Estimated Income','Superannuation Savings']
# univariate analysis

plt.figure(figsize=(8, 4))
for i,col in enumerate(numerical_cols):
  plt.subplot(2,1,i+1)
  sns.histplot(df[col],kde='true')
  plt.title(f'histogram of {col}')
  plt.xlabel(col)
  plt.ylabel('count')
  plt.show()

numerical_cols=['Estimated Income','Credit Card Balance','Bank Deposits','Bank Loans']
correlation_matrix =df [numerical_cols].corr()
plt.figure(figsize=(4,4))
sns.heatmap(correlation_matrix,annot=True,cmap='coolwarm',fmt='.2f')
plt.title('Correlation Matrix')
plt.show()

